development:
  adapter: postgresql
  encoding: unicode
  database: shortly_development
  pool: 5
  username: rsj
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: shortly_test
  pool: 5
  username: rsj
  password: 
